addons:
  youtube:
    enabled: true
    tags: 
      - "Youtube"
  openlink:
    enabled: true
    tags:
      - "News/Code"
      - "News/World"
  yt_suggest:
    enabled: true
    tags:
      - "Youtube/Suggestions"
