addons:
  youtube:
    enabled: true
    tags: 
      - "Youtube"
  openlink:
    enabled: true
    tags:
      - "News/Code"
      - "News/World"
  yt_suggest:
    enabled: true
    logging: false
    browser: "firefox"
    tags:
      - "Youtube/Suggestions"
  telegram:
    enabled: true
    tags:
      - "Telegram"
